-
  name: 'Default'
  uriPattern:    ''
  defaults:
    '@package':    Sifpe
    '@controller': Empresa
    '@action':     index
    '@format':     html
-
  name: 'empresa'
  uriPattern:    'empresa(/)'
  defaults:
    '@package':    Sifpe
    '@controller': Empresa
    '@action':     index
    '@format':     html
-
  name: 'empresa'
  uriPattern:    'empresa/index'
  defaults:
    '@package':    Sifpe
    '@controller': Empresa
    '@action':     index
    '@format':     html
-
  name: 'empresa'
  uriPattern:    'empresa/{@action}(/index.{@format})'
  defaults:
    '@package':    Sifpe
    '@controller': Empresa
    '@action':     list
    '@format':     json