-
  name: 'Default'
  uriPattern:    ''
  defaults:
    '@package':    Sifpe
    '@controller': Empresa
    '@action':     index
    '@format':     html
##########################################################
###  Empresa
##########################################################
-
  name: 'empresa default'
  uriPattern:    'empresa(/)'
  defaults:
    '@package':    Sifpe
    '@controller': Empresa
    '@action':     index
    '@format':     html
-
  name: 'empresa index'
  uriPattern:    'empresa/index'
  defaults:
    '@package':    Sifpe
    '@controller': Empresa
    '@action':     index
    '@format':     html
-
  name: 'empresa actions'
  uriPattern:    'empresa/{@action}(/index.{@format})'
  defaults:
    '@package':    Sifpe
    '@controller': Empresa
    '@action':     list
    '@format':     json
##########################################################
###  Grupo Cuenta
##########################################################
-
  name: 'grupocuenta default'
  uriPattern:    'grupocuenta(/)'
  defaults:
    '@package':    Sifpe
    '@controller': GrupoCuenta
    '@action':     index
    '@format':     html
-
  name: 'grupocuenta index'
  uriPattern:    'grupocuenta/index'
  defaults:
    '@package':    Sifpe
    '@controller': GrupoCuenta
    '@action':     index
    '@format':     html
-
  name: 'grupocuenta actions'
  uriPattern:    'grupocuenta/{@action}(/index.{@format})'
  defaults:
    '@package':    Sifpe
    '@controller': GrupoCuenta
    '@action':     list
    '@format':     json
##########################################################
###  Cuenta
##########################################################
-
  name: 'cuenta default'
  uriPattern:    'cuenta(/)'
  defaults:
    '@package':    Sifpe
    '@controller': Cuenta
    '@action':     index
    '@format':     html
-
  name: 'cuenta index'
  uriPattern:    'cuenta/index'
  defaults:
    '@package':    Sifpe
    '@controller': Cuenta
    '@action':     index
    '@format':     html
-
  name: 'cuenta actions'
  uriPattern:    'cuenta/{@action}(/index.{@format})'
  defaults:
    '@package':    Sifpe
    '@controller': Cuenta
    '@action':     list
    '@format':     json